# write_pres.ps1  — assembles presentation.tex from string segments
$out = 'presentation.tex'
$lines = [System.Collections.Generic.List[string]]::new()

function A($s){ $script:lines.Add($s) }

A '% ============================================================'
A '%  Thesis Defense Presentation  ---  31 slides + backup, ~30 min'
A '%  Topology-Optimized GaP Nanostructures for Valley-to-OAM'
A '%  Author:  Cheng, Yin-Jie  |  Advisor: Dr. Jhih-Sheng Wu'
A '%  Dept. of Photonics, NYCU  |  August 2026'
A '% ============================================================'
A '\documentclass[aspectratio=169, 10pt]{beamer}'
A '\usetheme{Madrid}'
A '\usecolortheme{default}'
A '\definecolor{NYCUblue}{RGB}{0,56,116}'
A '\definecolor{NYCUgold}{RGB}{200,155,60}'
A '\definecolor{lightblue}{RGB}{220,235,255}'
A '\definecolor{darkgray}{RGB}{60,60,60}'
A '\definecolor{accentred}{RGB}{180,30,30}'
A '\definecolor{accentgreen}{RGB}{20,120,60}'
A '\definecolor{mutezone}{RGB}{255,245,220}'
A '\setbeamercolor{palette primary}{bg=NYCUblue, fg=white}'
A '\setbeamercolor{palette secondary}{bg=NYCUblue!80, fg=white}'
A '\setbeamercolor{palette tertiary}{bg=NYCUblue!60, fg=white}'
A '\setbeamercolor{palette quaternary}{bg=NYCUblue, fg=white}'
A '\setbeamercolor{frametitle}{bg=NYCUblue, fg=white}'
A '\setbeamercolor{title}{fg=NYCUblue}'
A '\setbeamercolor{subtitle}{fg=NYCUgold}'
A '\setbeamercolor{block title}{bg=NYCUblue!90, fg=white}'
A '\setbeamercolor{block body}{bg=lightblue}'
A '\setbeamercolor{block title alerted}{bg=accentred!85, fg=white}'
A '\setbeamercolor{block body alerted}{bg=accentred!10}'
A '\setbeamercolor{block title example}{bg=accentgreen!80, fg=white}'
A '\setbeamercolor{block body example}{bg=accentgreen!8}'
A '\setbeamercolor{structure}{fg=NYCUblue}'
A '\setbeamercolor{item}{fg=NYCUblue}'
A '\usefonttheme{professionalfonts}'
A '\setbeamerfont{title}{size=\large, series=\bfseries}'
A '\setbeamerfont{frametitle}{size=\normalsize, series=\bfseries}'
A '\setbeamerfont{block title}{size=\small, series=\bfseries}'
A '\usepackage{amsmath, amssymb, bm}'
A '\usepackage{graphicx}'
A '\usepackage{booktabs}'
A '\usepackage{multirow}'
A '\usepackage{multicol}'
A '\usepackage{tikz}'
A '\usetikzlibrary{arrows.meta, shapes, positioning, fit, backgrounds, calc}'
A '\usepackage{xcolor}'
A '\usepackage{hyperref}'
A '\usepackage{array}'
A '\usepackage{colortbl}'
A '\usepackage{pgfplots}'
A '\pgfplotsset{compat=1.18}'
A '\newcommand{\highlight}[1]{\textcolor{NYCUgold}{\textbf{#1}}}'
A '\newcommand{\red}[1]{\textcolor{accentred}{\textbf{#1}}}'
A '\newcommand{\grn}[1]{\textcolor{accentgreen}{\textbf{#1}}}'
A '\setbeamertemplate{footline}{%'
A '  \leavevmode%'
A '  \hbox{%'
A '    \begin{beamercolorbox}[wd=.33\paperwidth,ht=2.25ex,dp=1ex,center]{palette primary}%'
A '      \usebeamerfont{author in head/foot}\insertshortauthor'
A '    \end{beamercolorbox}%'
A '    \begin{beamercolorbox}[wd=.47\paperwidth,ht=2.25ex,dp=1ex,center]{palette secondary}%'
A '      \usebeamerfont{title in head/foot}\insertshorttitle'
A '    \end{beamercolorbox}%'
A '    \begin{beamercolorbox}[wd=.20\paperwidth,ht=2.25ex,dp=1ex,right]{palette primary}%'
A '      \usebeamerfont{date in head/foot}%'
A '      \insertframenumber{} / \inserttotalframenumber\hspace*{2ex}'
A '    \end{beamercolorbox}}%'
A '  \vskip0pt%'
A '}'
A '\setbeamertemplate{navigation symbols}{}'
A '\title[Valley-to-OAM via Topology Optimization]{%'
A '  Topology-Optimized All-Dielectric GaP Nanostructures\\'
A '  for Converting Valley-Polarized WS$_2$ Exciton Emission\\'
A '  into High-Purity Laguerre--Gaussian Beams%'
A '}'
A '\author[Cheng, Yin-Jie]{\textbf{Cheng, Yin-Jie}\\[4pt]{\small Advisor: Prof.\ Jhih-Sheng Wu}}'
A '\institute[NYCU]{Department of Photonics\\National Yang Ming Chiao Tung University}'
A '\date{August 2026}'
A '\begin{document}'
A ''
A '% [S01] Title'
A '\begin{frame}[plain]'
A '  \vspace{-0.3cm}'
A '  \titlepage'
A '  \vspace{-0.7cm}'
A '  \begin{columns}[c]'
A '    \column{0.48\textwidth}'
A '      \centering'
A '      \includegraphics[width=\textwidth,height=3.0cm,keepaspectratio]{img/018_structure_iter_282_beta_512.00.png}\\'
A '      {\tiny Optimized GaP/air nanostructure ($\ell=1$)}'
A '    \column{0.48\textwidth}'
A '      \centering'
A '      \includegraphics[width=\textwidth,height=3.0cm,keepaspectratio]{img/018_ff_iter_282_beta_512.00.png}\\'
A '      {\tiny Far-field LG$_{1,0}$ mode (purity 98.66\%)}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% [S02] Outline'
A '\begin{frame}{Outline}'
A '  \tableofcontents[hideallsubsections]'
A '\end{frame}'
A ''
A '\section{Background \& Motivation}'
A ''
A '% [S03] Why OAM'
A '\begin{frame}{OAM Light: A New Degree of Freedom}'
A '  \begin{columns}[T]'
A '    \column{0.54\textwidth}'
A '      \begin{block}{Orbital Angular Momentum (OAM)}'
A '        \begin{itemize}'
A '          \item Each photon carries $L_z = \ell\hbar$, \quad $\ell \in \mathbb{Z}$'
A '          \item OAM modes with different $\ell$ are mutually \textbf{orthogonal}'
A '          \item Unlimited, independent multiplexing channels'
A '          \item Boosts spectral efficiency \textbf{without} extra bandwidth'
A '        \end{itemize}'
A '      \end{block}'
A '      \vspace{4pt}'
A '      \begin{alertblock}{Bottleneck: Chip-Scale Generation}'
A '        Spiral phase plates, SLMs are \red{bulky \& passive}\\'
A '        Metasurfaces: compact but still \red{passive} (external illumination)\\[4pt]'
A '        \textbf{Goal:} active, integrated, valley-controlled OAM source on chip'
A '      \end{alertblock}'
A '    \column{0.43\textwidth}'
A '      \centering'
A '      \begin{tikzpicture}[scale=0.82, font=\footnotesize]'
A '        \foreach \l/\col/\ypos in {0/blue!60/3.0, 1/NYCUblue/2.0, 2/NYCUgold/1.0, 3/accentred/0.0}{'
A '          \draw[\col, thick] (0,\ypos+0.35) ellipse (0.18 and 0.32);'
A '          \node[right, \col] at (0.25,\ypos+0.35) {$\ell=\l$};'
A '        }'
A '        \node[above, NYCUblue, font=\scriptsize\bfseries] at (0,3.55){Helical wavefronts};'
A '      \end{tikzpicture}'
A '      \vspace{6pt}'
A '      {\footnotesize LG$_{p=0}$ intensity profiles:}\\[4pt]'
A '      \begin{tikzpicture}[scale=0.72, font=\tiny]'
A '        \foreach \i in {0,1,2,3}{'
A '          \pgfmathsetmacro{\ri}{0.12+\i*0.09}'
A '          \pgfmathsetmacro{\rinner}{\i*0.055}'
A '          \fill[NYCUblue!\the\numexpr 80-\i*15\relax, draw=none]({\i*1.15},0) circle (\ri);'
A '          \fill[white, draw=none]({\i*1.15},0) circle (\rinner);'
A '          \node[below] at ({\i*1.15},-0.30) {$\ell=\i$};'
A '        }'
A '      \end{tikzpicture}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% [S04] WS2'
A '\begin{frame}{The Active Chiral Source: Monolayer WS$_2$ and Valley Physics}'
A '  \begin{columns}[T]'
A '    \column{0.50\textwidth}'
A '      \begin{block}{Monolayer WS$_2$ (TMD)}'
A '        \begin{itemize}'
A '          \item Broken inversion symmetry $\Rightarrow D_{3h}$'
A '          \item \textbf{Direct bandgap} at $K$ and $K'"'"'$ valley points'
A '          \item Strong SOC $\Rightarrow$ \textbf{spin--valley locking}'
A '          \item Room-T stable excitons (0.3--0.5\,eV $\gg k_BT$)'
A '        \end{itemize}'
A '      \end{block}'
A '      \vspace{4pt}'
A '      \begin{alertblock}{Valley Selection Rules}'
A '        \centering'
A '        \begin{tabular}{ccc}'
A '          \toprule'
A '          Valley & Excitation & Emission \\'
A '          \midrule'
A '          $K$  & LCP ($\sigma^-$) & LCP ($\sigma^-$) \\'
A '          $K'"'"'$ & RCP ($\sigma^+$) & RCP ($\sigma^+$) \\'
A '          \bottomrule'
A '        \end{tabular}\\[4pt]'
A '        {\small Chiral emission is \textbf{intrinsic} --- no filter needed}'
A '      \end{alertblock}'
A '    \column{0.47\textwidth}'
A '      \centering'
A '      \includegraphics[width=0.88\textwidth,height=2.7cm,keepaspectratio]{img/TMDs_structure.jpg}\\'
A '      {\tiny TMD crystal lattice (W gray, S yellow)}\\[6pt]'
A '      \includegraphics[width=0.88\textwidth,height=2.7cm,keepaspectratio]{img/WS2_8points_markers.png}\\'
A '      {\tiny WS$_2$ band structure: A-exciton at $K$/$K'"'"'$ valleys}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% [S05] SAM to OAM'
A '\begin{frame}{SAM $\to$ OAM: Pancharatnam--Berry Phase}'
A '  \begin{columns}[T]'
A '    \column{0.52\textwidth}'
A '      \begin{block}{Geometric (PB) Phase}'
A '        For a nanoantenna rotated by $\theta$:'
A '        \[ \Phi_{\rm PB} = 2\theta \]'
A '        \begin{itemize}'
A '          \item Sign depends on polarization helicity'
A '          \item \textbf{Wavelength-independent} (geometric)'
A '        \end{itemize}'
A '      \end{block}'
A '      \vspace{4pt}'
A '      \begin{exampleblock}{OAM Encoding}'
A '        Azimuthally: $\theta(\phi)=q\phi$'
A '        \[ \Rightarrow \text{topological charge } \ell = \mp 2q \]'
A '        Valley SAM $\xrightarrow{\text{PB phase}}$ far-field OAM'
A '      \end{exampleblock}'
A '      \vspace{4pt}'
A '      \begin{alertblock}{Key Insight}'
A '        \textbf{Inverse design} finds optimal nanostructure maximizing SAM$\to$OAM fidelity \textbf{without} prescribing geometry'
A '      \end{alertblock}'
A '    \column{0.45\textwidth}'
A '      \centering'
A '      \begin{tikzpicture}[scale=0.88, font=\footnotesize]'
A '        \draw[thick, NYCUblue] (0,0) circle (1.2);'
A '        \fill[NYCUblue]  (0, 1.2) circle (3pt) node[above]{\tiny RCP $\sigma^+$};'
A '        \fill[accentred] (0,-1.2) circle (3pt) node[below]{\tiny LCP $\sigma^-$};'
A '        \draw[NYCUgold, thick, ->](0,1.2) arc[start angle=90,end angle=-90,radius=1.2] node[midway,right=2pt]{\tiny $\Phi_{\rm PB}=2\theta$};'
A '        \node[NYCUblue,font=\scriptsize] at (0, 0.0) {Poincar\`{e}};'
A '        \node[NYCUblue,font=\scriptsize] at (0,-0.3) {sphere};'
A '      \end{tikzpicture}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% [S06] Timeline 1'
A '\begin{frame}{Timeline I: Metasurface-Based OAM Generation}'
A '  \begin{columns}[T]'
A '    \column{0.88\textwidth}'
A '      \small\renewcommand{\arraystretch}{1.15}'
A '      \begin{tabular}{>{\bfseries}cp{9.0cm}c}'
A '        \toprule'
A '        Year & Key Contribution & Purity \\'
A '        \midrule'
A '        \rowcolor{lightblue}'
A '        2014 & Karimi --- L-shaped Au arrays, geometric-phase OAM (visible) & $\sim$64\% \\'
A '        2016 & Guo --- combined geometric + propagation phase, continuous shape & $>$90\% \\'
A '        \rowcolor{lightblue}'
A '        2017 & Liu --- \textit{perfect vortex} (ring size $\perp \ell$) & --- \\'
A '        2018 & Bi --- metasurface OAM multiplexing in mm-wave & --- \\'
A '        \rowcolor{lightblue}'
A '        2020 & Sroor --- TiO$_2$ inside laser cavity; $\ell=100$ & $\sim$90\% \\'
A '        2021 & Zhou --- TiO$_2$ perfect vortex, tunable ring and ellipticity & --- \\'
A '        \midrule'
A '        \rowcolor{NYCUblue!18}'
A '        \textbf{This work} & \textbf{Inverse-designed GaP + active WS$_2$, $\ell=0$--5, valley contrast $>$100:1} & \textbf{82--98\%} \\'
A '        \bottomrule'
A '      \end{tabular}'
A '    \column{0.10\textwidth}'
A '      \vspace{0.6cm}'
A '      \begin{tikzpicture}'
A '        \node[draw=NYCUgold,fill=mutezone,rounded corners=3pt,minimum width=1.1cm,minimum height=4.5cm,font=\tiny\itshape,text=darkgray,align=center,rotate=90] at (0,0){Committee annotation space};'
A '      \end{tikzpicture}'
A '  \end{columns}'
A '  \vspace{4pt}'
A '  {\small \textbf{Gap:} All prior works use \red{passive external} illumination. None integrates an \grn{active valley-polarized} source.}'
A '\end{frame}'
A ''
A '% [S07] Timeline 2'
A '\begin{frame}{Timeline II: Valley-Chiral Photonics}'
A '  \begin{columns}[T]'
A '    \column{0.88\textwidth}'
A '      \small\renewcommand{\arraystretch}{1.15}'
A '      \begin{tabular}{>{\bfseries}cp{9.6cm}}'
A '        \toprule'
A '        Year & Key Contribution \\'
A '        \midrule'
A '        \rowcolor{lightblue}'
A '        2012 & Xiao --- spin--valley locking theory; valley-selective optical rules in TMDs \\'
A '        2012 & Mak, Zeng --- experimental valley polarization in MoS$_2$ / WSe$_2$ \\'
A '        \rowcolor{lightblue}'
A '        2013 & Gan --- first 2D material on GaP photonic crystal microcavity \\'
A '        2014 & Wu --- GaP photonic crystal controls TMD spontaneous emission \\'
A '        \rowcolor{lightblue}'
A '        2018 & Gong --- WS$_2$ + Ag nanowire; valley directional coupling 90\% \\'
A '        2019 & Sortino --- GaP nanoantenna + WSe$_2$; PL enhancement $10^4\times$ \\'
A '        \rowcolor{lightblue}'
A '        2020 & Rong --- Si metasurface, photonic Rashba; directional valley beam \\'
A '        2023 & Rong --- WS$_2$ + Kagome crystal; room-T spin--valley laser \\'
A '        \rowcolor{lightblue}'
A '        2025 & Pan --- Si chiral metasurface + quasi-BIC; room-T valley-selective CP \\'
A '        \midrule'
A '        \rowcolor{NYCUblue!18}'
A '        \textbf{This work} & \textbf{GaP inverse-designed + WS$_2$: valley $\to$ high-purity LG OAM beam} \\'
A '        \bottomrule'
A '      \end{tabular}'
A '    \column{0.10\textwidth}'
A '      \vspace{0.6cm}'
A '      \begin{tikzpicture}'
A '        \node[draw=NYCUgold,fill=mutezone,rounded corners=3pt,minimum width=1.1cm,minimum height=4.5cm,font=\tiny\itshape,text=darkgray,align=center,rotate=90] at (0,0){Committee annotation space};'
A '      \end{tikzpicture}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% [S08] Timeline 3'
A '\begin{frame}{Timeline III: Inverse-Designed Nanophotonics \& Research Gap}'
A '  \begin{columns}[T]'
A '    \column{0.88\textwidth}'
A '      \small\renewcommand{\arraystretch}{1.15}'
A '      \begin{tabular}{>{\bfseries}cp{9.4cm}}'
A '        \toprule'
A '        Year & Key Contribution \\'
A '        \midrule'
A '        \rowcolor{lightblue}'
A '        2011 & Jensen --- topology optimization framework for nanophotonics \\'
A '        2018 & Molesky --- systematic review: inverse design for nanophotonics \\'
A '        \rowcolor{lightblue}'
A '        2022 & Li --- topology-optimized metasurface, asymmetric beam deflection \\'
A '        2023 & Gelly --- inverse design + TMD for cavity coupling \\'
A '        \rowcolor{lightblue}'
A '        2023 & White --- inverse-designed Si OAM emitter (passive; no valley selectivity) \\'
A '        2023 & Li --- TMD BIC photonic crystal; valley $\to$ OAM (\red{purity not quantified}) \\'
A '        \rowcolor{lightblue}'
A '        2024 & Wang --- full-Stokes polarimetry via inverse-designed metasurface \\'
A '        2025 & Choi --- large-NA achromatic metalens by inverse design \\'
A '        \midrule'
A '        \rowcolor{NYCUblue!18}'
A '        \textbf{This work} & \textbf{First: active valley source + inverse design + quantified LG purity + contrast $>$100:1} \\'
A '        \bottomrule'
A '      \end{tabular}'
A '    \column{0.10\textwidth}'
A '      \vspace{0.6cm}'
A '      \begin{tikzpicture}'
A '        \node[draw=NYCUgold,fill=mutezone,rounded corners=3pt,minimum width=1.1cm,minimum height=4.5cm,font=\tiny\itshape,text=darkgray,align=center,rotate=90] at (0,0){Committee annotation space};'
A '      \end{tikzpicture}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% [S09] Research Gap'
A '\begin{frame}{Research Gap \& Thesis Objectives}'
A '  \begin{columns}[T]'
A '    \column{0.52\textwidth}'
A '      \centering'
A '      \begin{tikzpicture}[font=\small, scale=0.92]'
A '        \draw[thick, NYCUblue] (0,0) rectangle (5,4);'
A '        \draw[dashed, gray] (2.5,0) -- (2.5,4);'
A '        \draw[dashed, gray] (0,2)   -- (5,2);'
A '        \node[font=\footnotesize,gray] at (1.25,4.3) {Passive};'
A '        \node[font=\footnotesize,gray] at (3.75,4.3) {Active};'
A '        \node[font=\footnotesize,gray,rotate=90] at (-0.4,1.0) {Forward};'
A '        \node[font=\footnotesize,gray,rotate=90] at (-0.4,3.0) {Inverse};'
A '        \node[fill=NYCUblue!20,rounded corners,align=center,font=\footnotesize,minimum width=2cm] at (1.25,1.0) {Sroor 2020\\Karimi 2014};'
A '        \node[fill=NYCUblue!20,rounded corners,align=center,font=\footnotesize,minimum width=2cm] at (3.75,1.0) {Li 2023\\(BIC)};'
A '        \node[fill=NYCUblue!20,rounded corners,align=center,font=\footnotesize,minimum width=2cm] at (1.25,3.0) {White 2023\\(Si, passive)};'
A '        \node[fill=NYCUgold!60,draw=NYCUgold,rounded corners,align=center,font=\footnotesize\bfseries,minimum width=2.2cm,minimum height=1.0cm] at (3.75,3.0) {\textbf{This work}\\GaP + WS$_2$};'
A '        \node[accentred,font=\tiny] at (3.75,2.15) {previously EMPTY};'
A '      \end{tikzpicture}'
A '    \column{0.45\textwidth}'
A '      \begin{block}{Three Thesis Objectives}'
A '        \begin{enumerate}'
A '          \item Build 3D FDTD + adjoint framework for WS$_2$ + GaP metasurface'
A '          \item Inversely design valley-controlled LG emitters ($\ell=0$--$5$)'
A '          \item Quantify: purity, phase winding, chirality, inter-valley contrast'
A '        \end{enumerate}'
A '      \end{block}'
A '      \vspace{6pt}'
A '      \begin{exampleblock}{Key Claim}'
A '        \textbf{First platform simultaneously:}\\'
A '        Active valley source \textbf{+} Inverse design\\'
A '        \textbf{+} Quantified LG purity\\'
A '        \textbf{+} Valley contrast $>$100:1'
A '      \end{exampleblock}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% [S10] LG Fundamentals'
A '\begin{frame}{LG Mode Fundamentals}'
A '  \begin{columns}[T]'
A '    \column{0.52\textwidth}'
A '      \begin{block}{LG$_{p,\ell}$ Complex Amplitude}'
A '        \small'
A '        \[ u_{p,\ell} \propto \!\left(\!\frac{\sqrt{2}r}{w}\!\right)^{|\ell|} L_p^{|\ell|}\!\!\left(\frac{2r^2}{w^2}\right) e^{-r^2/w^2}\, \underbrace{e^{i\ell\phi}}_{\text{helical phase}} \]'
A '        \begin{itemize}'
A '          \item $\ell$: topological charge; $L_z=\ell\hbar$ per photon'
A '          \item $|\ell|\ge1$: phase singularity at $r=0$ $\Rightarrow$ \textbf{doughnut}'
A '          \item Peak ring: $r_{\rm peak}=w_0\sqrt{|\ell|/2}$'
A '        \end{itemize}'
A '      \end{block}'
A '      \vspace{4pt}'
A '      \begin{alertblock}{Key for Discussion}'
A '        Ring grows with $\ell$ but \textbf{design area is fixed} at 4.5\,$\mu$m\\'
A '        $\Rightarrow$ physical limit at high $\ell$ (foreshadows Discussion)'
A '      \end{alertblock}'
A '    \column{0.45\textwidth}'
A '      \centering'
A '      \includegraphics[width=\textwidth,height=2.5cm,keepaspectratio]{img/017_ff_iter_257_beta_512.00.png}\\'
A '      {\tiny $\ell=0$: Gaussian}\\[3pt]'
A '      \includegraphics[width=\textwidth,height=2.5cm,keepaspectratio]{img/018_ff_iter_282_beta_512.00.png}\\'
A '      {\tiny $\ell=1$: doughnut + single-arm spiral}\\[3pt]'
A '      \includegraphics[width=\textwidth,height=2.5cm,keepaspectratio]{img/013_ff_iter_282_beta_512.00.png}\\'
A '      {\tiny $\ell=2$: wider ring + 2-arm spiral}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '\section{Methodology}'
A ''
A '% [S11] Section Divider'
A '\begin{frame}[plain]'
A '  \begin{tikzpicture}[remember picture, overlay]'
A '    \fill[NYCUblue](current page.south west) rectangle (current page.north east);'
A '    \node[white,font=\Huge\bfseries] at (current page.center){2.\ Methodology};'
A '    \node[white,font=\large] at ([yshift=-1.2cm]current page.center){FDTD $\cdot$ Physical Model $\cdot$ Topology Optimization $\cdot$ Metrics};'
A '  \end{tikzpicture}'
A '\end{frame}'
A ''
A '% [S12] FDTD'
A '\begin{frame}{Numerical Framework: FDTD + MEEP}'
A '  \begin{columns}[T]'
A '    \column{0.52\textwidth}'
A '      \begin{block}{FDTD Method}'
A '        \[ \nabla\times\mathbf{E}=-\frac{\partial\mathbf{B}}{\partial t},\quad \nabla\times\mathbf{H}=\frac{\partial\mathbf{D}}{\partial t}+\mathbf{J} \]'
A '        \begin{itemize}'
A '          \item Staggered Yee grid + leapfrog time scheme'
A '          \item CFL condition ensures stability'
A '          \item PML absorbing boundaries'
A '        \end{itemize}'
A '      \end{block}'
A '      \vspace{4pt}'
A '      \begin{exampleblock}{MEEP (MIT, open-source)}'
A '        \begin{itemize}'
A '          \item Arbitrary non-uniform media'
A '          \item \textbf{Adjoint optimization module}: differentiable computational graph'
A '          \item Auto gradient backpropagation to all $5.1\times10^4$ variables'
A '        \end{itemize}'
A '      \end{exampleblock}'
A '    \column{0.45\textwidth}'
A '      \centering'
A '      \includegraphics[width=\textwidth,keepaspectratio]{img/xz_structure_waist.png}\\'
A '      {\tiny Cross-section: PML / Diamond / WS$_2$ dipole / GaP--Air design layer / NF monitor (red dashed) / Air / PML.}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% [S13] Physical Model'
A '\begin{frame}{Physical Model: Geometry, Materials \& Source}'
A '  \begin{columns}[T]'
A '    \column{0.50\textwidth}'
A '      \begin{block}{Layer Stack}'
A '        \small'
A '        \begin{tabular}{ll}'
A '          Diamond substrate & $n=2.40$ \\'
A '          WS$_2$ monolayer  & $n=2.40$, 1 grid \\'
A '          GaP design layer  & $n=3.31$, $t=0.257\;\mu$m \\'
A '          Air (above)       & $n=1$ \\'
A '        \end{tabular}\\[4pt]'
A '        $t$: $\Delta n\cdot t=\lambda/2 \Rightarrow$ full $2\pi$ phase at $\lambda=0.593\;\mu$m'
A '      \end{block}'
A '      \vspace{4pt}'
A '      \begin{exampleblock}{Design Parameters}'
A '        \begin{tabular}{ll}'
A '          Lateral size  & $4.5\times4.5\;\mu\text{m}^2$ \\'
A '          Resolution    & $50\;\text{pts}/\mu$m \\'
A '          DOF $N$       & $226^2\approx5.1\times10^4$ \\'
A '        \end{tabular}'
A '      \end{exampleblock}'
A '      \vspace{4pt}'
A '      \begin{alertblock}{WS$_2$ Dipole Source}'
A '        $K$-valley LCP: $\mathbf{p}=p_0[\hat{x}+i\hat{y}]e^{-i\omega_0 t}f(t)$\\'
A '        $K'"'"'$-valley RCP: $[\hat{x}-i\hat{y}]$ (cross-pol.\ test)'
A '      \end{alertblock}'
A '    \column{0.47\textwidth}'
A '      \centering'
A '      \includegraphics[width=0.92\textwidth,keepaspectratio]{img/xz_structure.png}\\[4pt]'
A '      {\tiny Simulation geometry. Far-field at $z=10\,z_R$.}\\[6pt]'
A '      \begin{tikzpicture}[font=\tiny]'
A '        \node[draw=NYCUgold,fill=mutezone,rounded corners=3pt,minimum width=4.4cm,minimum height=0.95cm,align=center,text=darkgray]{\textit{Why GaP vs.\ Si vs.\ TiO$_2$?}\\GaP: below indirect bandgap at 0.593\,$\mu$m, low-loss, e-beam litho compatible (Gan 2013)};'
A '      \end{tikzpicture}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% [S14] Design Variables'
A '\begin{frame}{Topology Optimization I: Design Variables \& Filtering}'
A '  \begin{columns}[T]'
A '    \column{0.52\textwidth}'
A '      \begin{block}{Design Variable: $\rho(\mathbf{x})\in[0,1]$}'
A '        \begin{itemize}'
A '          \item $\rho=0$: air;\quad $\rho=1$: GaP; no geometric prior'
A '          \item $\varepsilon(\mathbf{x})=\varepsilon_{\rm air}+\bar{\rho}(\varepsilon_{\rm GaP}-\varepsilon_{\rm air})$'
A '        \end{itemize}'
A '      \end{block}'
A '      \vspace{4pt}'
A '      \begin{exampleblock}{Conic Filter (min.\ feature 50\,nm)}'
A '        Smooths $\rho\to\tilde{\rho}$; prevents checkerboard'
A '      \end{exampleblock}'
A '      \vspace{4pt}'
A '      \begin{exampleblock}{Tanh Projection (binarization)}'
A '        $\bar{\rho}=\dfrac{\tanh(\beta\eta)+\tanh(\beta(\tilde{\rho}-\eta))}{\tanh(\beta\eta)+\tanh(\beta(1-\eta))}$\\[4pt]'
A '        \textbf{$\beta$ schedule}: $4\to512$ --- low $\beta$: explore; high $\beta$: sharp binary'
A '      \end{exampleblock}'
A '    \column{0.45\textwidth}'
A '      \centering'
A '      \begin{tikzpicture}[font=\footnotesize,scale=0.88,node distance=0.5cm]'
A '        \node[draw=NYCUblue,fill=lightblue,rounded corners,minimum width=3.0cm,minimum height=0.65cm](raw){Raw $\rho$ (grayscale)};'
A '        \node[draw=NYCUblue,fill=lightblue,rounded corners,minimum width=3.0cm,minimum height=0.65cm,below=of raw](filt){Filtered $\tilde{\rho}$};'
A '        \node[draw=NYCUblue,fill=NYCUblue!60,text=white,rounded corners,minimum width=3.0cm,minimum height=0.65cm,below=of filt](proj){Binary $\bar{\rho}$ (GaP/air)};'
A '        \draw[->,thick,NYCUblue](raw) -- node[right,font=\tiny]{conic filter}(filt);'
A '        \draw[->,thick,NYCUblue](filt) -- node[right,font=\tiny]{tanh + $\beta$ anneal}(proj);'
A '      \end{tikzpicture}\\[10pt]'
A '      \includegraphics[width=0.72\textwidth,keepaspectratio]{img/018_structure_iter_282_beta_512.00.png}\\'
A '      {\tiny Final binarized $\ell=1$ structure ($\beta=512$). Black=GaP, White=air}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% [S15] FOM + Adjoint'
A '\begin{frame}{Topology Optimization II: FOM \& Adjoint Method}'
A '  \begin{columns}[T]'
A '    \column{0.52\textwidth}'
A '      \begin{block}{Figure of Merit}'
A '        \[ \text{FOM}=(1+\alpha)\log|\text{Overlap}|^2-\log P_{\rm sim} \]'
A '        \begin{itemize}'
A '          \item $\alpha=0.1$: balances shape vs.\ coupling power'
A '          \item Log regularization prevents pathological convergence'
A '        \end{itemize}'
A '      \end{block}'
A '      \vspace{4pt}'
A '      \begin{exampleblock}{Adjoint Gradient}'
A '        \[ \frac{\partial\text{FOM}}{\partial\rho_j}\propto \mathrm{Re}\!\left[\int_{\Omega_j} \mathbf{E}_{\rm adj}\cdot\frac{\partial\varepsilon}{\partial\rho_j} \mathbf{E}_{\rm fwd}\,dV\right] \]'
A '        \begin{enumerate}'
A '          \item \textbf{Forward} FDTD $\to\mathbf{E}_{\rm fwd}$'
A '          \item \textbf{Adjoint} FDTD $\to\mathbf{E}_{\rm adj}$'
A '          \item Pointwise product $\to$ full gradient'
A '        \end{enumerate}'
A '        Only \textbf{2 simulations} vs.\ $5.1\times10^4$ (FD)'
A '      \end{exampleblock}'
A '    \column{0.45\textwidth}'
A '      \centering'
A '      \begin{tikzpicture}[font=\small,scale=0.88]'
A '        \draw[thick,->](0,0)--(0,4.2) node[above]{Sim.\ cost};'
A '        \draw[thick,->](0,0)--(4,0) node[right]{$N$};'
A '        \draw[accentred,very thick](0,0)--(3.5,3.5) node[right,font=\footnotesize]{FD: $\mathcal{O}(N)$};'
A '        \draw[accentgreen,very thick,dashed](0,0.45)--(3.5,0.45) node[right,font=\footnotesize]{Adjoint: $\mathcal{O}(1)$};'
A '        \draw[<->,NYCUgold,thick](1.8,0.45)--(1.8,1.80);'
A '        \node[right,font=\tiny,NYCUgold] at (1.85,1.15){\highlight{$\times25{,}000\times$}};'
A '        \fill[accentred](0,0) circle(2pt);'
A '        \fill[accentgreen](0,0.45) circle(2pt);'
A '      \end{tikzpicture}\\[6pt]'
A '      \begin{alertblock}{\centering Practical Impact}'
A '        \footnotesize Topology optimization with $5.1\times10^4$ free variables is \textbf{only feasible} thanks to the adjoint method.'
A '      \end{alertblock}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% [S16] Workflow'
A '\begin{frame}{Topology Optimization III: N2F, MMA \& Full Workflow}'
A '  \begin{columns}[T]'
A '    \column{0.55\textwidth}'
A '      \centering'
A '      \includegraphics[width=\textwidth,keepaspectratio]{img/to_workflow.png}\\'
A '      {\tiny Init $\to$ Forward FDTD $\to$ N2F $\to$ FOM $\to$ Adjoint FDTD $\to$ Gradient $\to$ MMA update. $\beta$ increases until $\beta_{\rm max}=512$.}'
A '    \column{0.42\textwidth}'
A '      \begin{block}{N2F Transformation}'
A '        $\mathbf{J}_s=\hat{n}\times\mathbf{H}$,\; $\mathbf{M}_s=-\hat{n}\times\mathbf{E}$\\'
A '        Propagated via Greens function\\[4pt]'
A '        Differentiable N2F allows adjoint gradients through the transformation'
A '      \end{block}'
A '      \vspace{5pt}'
A '      \begin{exampleblock}{MMA Optimizer}'
A '        Convex separable sub-problems\\'
A '        Dynamically adjusted step bounds\\'
A '        Bounds: $0\le\rho_j\le1$'
A '      \end{exampleblock}'
A '      \vspace{5pt}'
A '      \begin{block}{Convergence}'
A '        \begin{tabular}{ll}'
A '          $\beta$ range     & $4\to512$ \\'
A '          Iters per $\beta$ & 12--30 \\'
A '          Best iter max     & 282 \\'
A '        \end{tabular}'
A '      \end{block}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% [S17] Metrics'
A '\begin{frame}{Performance Metrics}'
A '  \begin{columns}[T]'
A '    \column{0.50\textwidth}'
A '      \begin{block}{\textcircled{1} Mode Overlap Integral}'
A '        \[ \text{Overlap}=\int_A\!\left(E_{ff,x}E_{t,x}^*+E_{ff,y}E_{t,y}^*\right)dA \]'
A '        $\Rightarrow$ \textbf{absolute coupling power}'
A '      \end{block}'
A '      \vspace{4pt}'
A '      \begin{block}{\textcircled{2} LG Mode Purity}'
A '        \[ \text{Purity}=\frac{|\text{Overlap}|^2}{P_{\rm sim}},\;P_{\rm target}=1 \]'
A '        \textbf{Normalized shape fidelity}; $\in[0,1]$'
A '      \end{block}'
A '    \column{0.47\textwidth}'
A '      \begin{block}{\textcircled{3} Phase Winding}'
A '        Sample LCP phase at $r_{\rm peak}=w_0\sqrt{|\ell|/2}$\\'
A '        Unwrapped $\Delta\phi$ should $=\ell\times2\pi$\\'
A '        \textbf{Target:} winding error $<1\%$'
A '      \end{block}'
A '      \vspace{4pt}'
A '      \begin{block}{\textcircled{4} Optical Chirality}'
A '        \[ C=\pi f\,\mathrm{Im}(\mathbf{E}^*\cdot\mathbf{H}) \]'
A '        $C>0$: LCP;\quad $C<0$: RCP dominant\\'
A '        Evaluated at near-field and $z=10\,z_R$'
A '      \end{block}'
A '      \vspace{4pt}'
A '      \begin{tikzpicture}[font=\tiny]'
A '        \node[draw=NYCUgold,fill=mutezone,rounded corners,minimum width=4.5cm,minimum height=0.75cm,align=center,text=darkgray]{Purity + $|\text{Overlap}|^2$ are complementary;\\both needed to evaluate performance};'
A '      \end{tikzpicture}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '\section{Results \& Discussion}'
A ''
A '% [S18] Section Divider'
A '\begin{frame}[plain]'
A '  \begin{tikzpicture}[remember picture, overlay]'
A '    \fill[NYCUblue](current page.south west) rectangle (current page.north east);'
A '    \node[white,font=\Huge\bfseries] at (current page.center){3.\ Results \& Discussion};'
A '    \node[white,font=\large] at ([yshift=-1.2cm]current page.center){Convergence $\cdot$ Structures $\cdot$ Far-Field $\cdot$ Chirality $\cdot$ Valley Selectivity};'
A '  \end{tikzpicture}'
A '\end{frame}'
A ''
A '% [S19] Convergence'
A '\begin{frame}{Optimization Convergence: $\beta$-Continuation}'
A '  \begin{columns}[T]'
A '    \column{0.50\textwidth}'
A '      \centering'
A '      \includegraphics[width=\textwidth,keepaspectratio]{img/018_FOM_history_staircase.png}\\'
A '      {\tiny $\ell=1$: best case. Steep rise; stable after $\beta>32$.}\\[5pt]'
A '      \includegraphics[width=\textwidth,keepaspectratio]{img/022_FOM_history_staircase.png}\\'
A '      {\tiny $\ell=5$: challenging. Lower final FOM; still stable.}'
A '    \column{0.47\textwidth}'
A '      \begin{block}{Convergence Pattern}'
A '        \begin{itemize}'
A '          \item Purple lines: $\beta$ switch points'
A '          \item Main structure forms \textbf{early} (low $\beta$)'
A '          \item High $\beta$ fine-tunes boundary sharpness'
A '          \item No oscillation or divergence'
A '        \end{itemize}'
A '      \end{block}'
A '      \vspace{5pt}'
A '      \begin{exampleblock}{Final Results}'
A '        \small\centering'
A '        \begin{tabular}{ccc}'
A '          \toprule'
A '          $\ell$ & Purity (\%) & FOM \\'
A '          \midrule'
A '          0 & 96.81 & 0.38 \\'
A '          1 & \textbf{98.66} & 0.39 \\'
A '          2 & 97.96 & 0.19 \\'
A '          3 & 94.13 & 0.23 \\'
A '          4 & 81.94 & $-$0.06 \\'
A '          5 & 82.62 & $-$0.05 \\'
A '          \bottomrule'
A '        \end{tabular}'
A '      \end{exampleblock}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% [S20] Structures'
A '\begin{frame}{Optimized Structures: Spiral Geometry Self-Emerges}'
A '  \begin{columns}[T]'
A '    \column{0.60\textwidth}'
A '      \centering'
A '      {\footnotesize GaP/air binary ($\beta=512$): \textbf{black}=GaP, \textbf{white}=air}\\[4pt]'
A '      \begin{tabular}{ccc}'
A '        \includegraphics[width=0.31\textwidth,keepaspectratio]{img/017_structure_iter_257_beta_512.00.png} &'
A '        \includegraphics[width=0.31\textwidth,keepaspectratio]{img/018_structure_iter_282_beta_512.00.png} &'
A '        \includegraphics[width=0.31\textwidth,keepaspectratio]{img/013_structure_iter_282_beta_512.00.png} \\'
A '        {\tiny (a) $\ell=0$} & {\tiny (b) $\ell=1$} & {\tiny (c) $\ell=2$} \\[4pt]'
A '        \includegraphics[width=0.31\textwidth,keepaspectratio]{img/020_structure_iter_282_beta_512.00.png} &'
A '        \includegraphics[width=0.31\textwidth,keepaspectratio]{img/021_structure_iter_267_beta_512.00.png} &'
A '        \includegraphics[width=0.31\textwidth,keepaspectratio]{img/022_structure_iter_282_beta_512.00.png} \\'
A '        {\tiny (d) $\ell=3$} & {\tiny (e) $\ell=4$} & {\tiny (f) $\ell=5$} \\'
A '      \end{tabular}'
A '    \column{0.38\textwidth}'
A '      \begin{block}{Key Observation}'
A '        \begin{itemize}'
A '          \item \textbf{No geometric prior} given'
A '          \item $\ell$-fold spiral symmetry \textbf{self-emerges}'
A '          \item Arm count = target $\ell$'
A '          \item Analogous to spiral phase plate'
A '          \item Peripheral features: scattering compensation'
A '        \end{itemize}'
A '      \end{block}'
A '      \vspace{5pt}'
A '      \begin{exampleblock}{As $\ell$ increases}'
A '        More arms + denser outer features\\'
A '        $\Rightarrow$ finer azimuthal phase density needed'
A '      \end{exampleblock}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% [S21] Performance Table'
A '\begin{frame}{Performance Summary: Purity \& Overlap}'
A '  \begin{columns}[T]'
A '    \column{0.50\textwidth}'
A '      \centering'
A '      \small\renewcommand{\arraystretch}{1.22}'
A '      \begin{tabular}{ccccc}'
A '        \toprule'
A '        $\ell$ & Mode & Purity(\%) & $|\text{Ov}|^2$ & FOM \\'
A '        \midrule'
A '        \rowcolor{accentgreen!20} 0 & LG$_{0,0}$ & 96.81 & 60.92 & 0.38 \\'
A '        \rowcolor{accentgreen!20} 1 & LG$_{1,0}$ & \textbf{98.66} & 53.88 & 0.39 \\'
A '        \rowcolor{accentgreen!20} 2 & LG$_{2,0}$ & 97.96 & 7.99  & 0.19 \\'
A '        \rowcolor{accentgreen!20} 3 & LG$_{3,0}$ & 94.13 & 18.69 & 0.23 \\'
A '        \rowcolor{NYCUgold!30}    4 & LG$_{4,0}$ & 81.94 & 4.00  & $-$0.06 \\'
A '        \rowcolor{NYCUgold!30}    5 & LG$_{5,0}$ & 82.62 & 3.96  & $-$0.05 \\'
A '        \bottomrule'
A '      \end{tabular}\\[5pt]'
A '      \begin{tikzpicture}[scale=0.78]'
A '        \begin{axis}['
A '          ybar,bar width=10pt,'
A '          xlabel={$\ell$},ylabel={Purity (\%)},'
A '          xtick={0,1,2,3,4,5},'
A '          ymin=70,ymax=102,ytick={70,80,90,100},'
A '          width=6.3cm,height=4.0cm,'
A '          tick label style={font=\tiny},label style={font=\small},'
A '          ymajorgrids,grid style=dashed,'
A '        ]'
A '          \addplot[fill=accentgreen!70,draw=accentgreen] coordinates{(0,96.81)(1,98.66)(2,97.96)(3,94.13)};'
A '          \addplot[fill=NYCUgold!80,draw=NYCUgold] coordinates{(4,81.94)(5,82.62)};'
A '          \draw[accentred,dashed,thick](axis cs:-0.5,80)--(axis cs:5.5,80) node[right,font=\tiny,accentred]{80\%};'
A '        \end{axis}'
A '      \end{tikzpicture}'
A '    \column{0.47\textwidth}'
A '      \begin{alertblock}{Purity vs.\ Overlap Decoupling}'
A '        \begin{itemize}'
A '          \item \textbf{Purity}: normalized shape (power-insensitive)'
A '          \item $|\text{Overlap}|^2$: absolute coupling energy'
A '          \item $\ell=2$: Purity=97.96\% but $|\text{Ov}|^2$=7.99'
A '          \item LG ring $r_{\rm peak}\propto\sqrt{\ell}$ grows; design fixed'
A '          \item Both metrics complementary and \textbf{necessary}'
A '        \end{itemize}'
A '      \end{alertblock}'
A '      \vspace{5pt}'
A '      \begin{tikzpicture}[font=\tiny]'
A '        \node[draw=NYCUgold,fill=mutezone,rounded corners,minimum width=4.5cm,minimum height=0.8cm,align=center,text=darkgray]{Why not higher purity for $\ell=4,5$?\\See physical limits discussion};'
A '      \end{tikzpicture}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% [S22] Far-Field'
A '\begin{frame}{Far-Field LG Mode: Phase \& Intensity at $z=10\,z_R$}'
A '  \centering'
A '  {\footnotesize Simulated results. Left=phase, Right=intensity for each $\ell$.}\\[4pt]'
A '  \begin{tabular}{ccc}'
A '    \includegraphics[width=0.31\textwidth,keepaspectratio]{img/018_ff_iter_282_beta_512.00.png} &'
A '    \includegraphics[width=0.31\textwidth,keepaspectratio]{img/020_ff_iter_282_beta_512.00.png} &'
A '    \includegraphics[width=0.31\textwidth,keepaspectratio]{img/022_ff_iter_282_beta_512.00.png} \\'
A '    {\tiny (a) $\ell=1$: \textbf{98.66\%}} & {\tiny (b) $\ell=3$: \textbf{94.13\%}} & {\tiny (c) $\ell=5$: \textbf{82.62\%}} \\[4pt]'
A '    \includegraphics[width=0.31\textwidth,keepaspectratio]{img/013_ff_iter_282_beta_512.00.png} &'
A '    \includegraphics[width=0.31\textwidth,keepaspectratio]{img/021_ff_iter_267_beta_512.00.png} &'
A '    \includegraphics[width=0.31\textwidth,keepaspectratio]{img/017_ff_iter_257_beta_512.00.png} \\'
A '    {\tiny (d) $\ell=2$: \textbf{97.96\%}} & {\tiny (e) $\ell=4$: \textbf{81.94\%}} & {\tiny (f) $\ell=0$: \textbf{96.81\%}} \\'
A '  \end{tabular}'
A '\end{frame}'
A ''
A '% [S23] Phase Winding'
A '\begin{frame}{Phase Winding: Topological Charge Accuracy}'
A '  \begin{columns}[T]'
A '    \column{0.50\textwidth}'
A '      \centering'
A '      \includegraphics[width=\textwidth,keepaspectratio]{img/018_ff_winding_iter_282_beta_512.00_rfraction_0.3885.png}\\'
A '      {\tiny $\ell=1$: $\Delta\phi=1.00\times2\pi$, error $<0.1\%$}\\[5pt]'
A '      \includegraphics[width=\textwidth,keepaspectratio]{img/022_ff_winding_iter_282_beta_512.00_rfraction_0.6176.png}\\'
A '      {\tiny $\ell=5$: $\Delta\phi\approx5.00\times2\pi$, error $<1\%$}'
A '    \column{0.47\textwidth}'
A '      \begin{block}{Protocol}'
A '        \begin{enumerate}'
A '          \item Sample LCP phase at $r_{\rm peak}$'
A '          \item Unwrap $\to$ total $\Delta\phi$'
A '          \item Compare with $\ell\times2\pi$'
A '        \end{enumerate}'
A '      \end{block}'
A '      \vspace{5pt}'
A '      \begin{exampleblock}{All Six Designs}'
A '        \small\centering'
A '        \begin{tabular}{cc}'
A '          \toprule'
A '          $\ell$ & Error \\'
A '          \midrule'
A '          0 & $\approx0$ \\'
A '          1 & $<0.1\%$ \\'
A '          2 & $0.5\%$ \\'
A '          3 & $<1\%$ \\'
A '          4 & $<1\%$ \\'
A '          5 & $<1\%$ \\'
A '          \bottomrule'
A '        \end{tabular}'
A '      \end{exampleblock}'
A '      \vspace{4pt}'
A '      \begin{alertblock}{Key Finding}'
A '        Even for $\ell=4,5$: topological charge \textbf{accurate}.\\'
A '        Purity drop = intensity profile, \textbf{not} phase error.'
A '      \end{alertblock}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% [S24] Chirality'
A '\begin{frame}{Optical Chirality: Near-to-Far-Field Evolution}'
A '  \begin{columns}[T]'
A '    \column{0.57\textwidth}'
A '      \centering'
A '      \includegraphics[width=\textwidth,keepaspectratio]{img/chirality_prop_0p0to0p9zr_Fixed_XY_360.png}\\'
A '      {\tiny Near-field ($z=0.0$--$0.9\,z_R$): mixed LCP/RCP from evanescent waves}\\[4pt]'
A '      \includegraphics[width=\textwidth,keepaspectratio]{img/chirality_prop_1to10zr_Fixed_XY_360.png}\\'
A '      {\tiny Far-field ($z=1.0$--$10.0\,z_R$): pure RCP recovered}'
A '    \column{0.40\textwidth}'
A '      \begin{block}{Chirality: $C=\pi f\,\mathrm{Im}(\mathbf{E}^*\cdot\mathbf{H})$}'
A '        Blue ($C>0$): LCP dominant\\'
A '        Red ($C<0$): RCP dominant'
A '      \end{block}'
A '      \vspace{5pt}'
A '      \begin{exampleblock}{Physical Interpretation}'
A '        \begin{itemize}'
A '          \item \textbf{Near field}: mixed LCP/RCP (evanescent + scattering)'
A '          \item \textbf{Transition} ($z\sim z_R$): evanescent decay'
A '          \item \textbf{Far field}: \textbf{pure RCP} restored'
A '        \end{itemize}'
A '      \end{exampleblock}'
A '      \vspace{4pt}'
A '      \begin{alertblock}{Conclusion}'
A '        OAM reshaping \& SAM \textbf{decoupled}.\\'
A '        No spurious spin--orbit coupling.\\'
A '        Far-field polarization purity preserved.'
A '      \end{alertblock}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% [S25] CLIMAX: Valley Selectivity'
A '\begin{frame}{Valley Selectivity: Cross-Polarization Test}'
A '  \begin{columns}[T]'
A '    \column{0.52\textwidth}'
A '      \centering'
A '      \begin{tikzpicture}'
A '        \node[draw=accentgreen,fill=accentgreen!12,rounded corners=5pt,minimum width=7.5cm,minimum height=0.72cm,font=\normalsize\bfseries]{\grn{\checkmark\ K-valley (LCP): Purity = 94.13\%}};'
A '      \end{tikzpicture}\\[4pt]'
A '      \includegraphics[width=0.85\textwidth,keepaspectratio]{img/020_ff_iter_282_beta_512.00.png}\\'
A '      {\tiny LCP source: clear $\ell=3$ doughnut + spiral phase.}\\[5pt]'
A '      \begin{tikzpicture}'
A '        \node[draw=accentred,fill=accentred!10,rounded corners=5pt,minimum width=7.5cm,minimum height=0.72cm,font=\normalsize\bfseries]{\red{\texttimes\ $K'"'"'$-valley (RCP): Purity = 0.84\%}};'
A '      \end{tikzpicture}\\[4pt]'
A '      \includegraphics[width=0.85\textwidth,keepaspectratio]{img/RCP_ff_iter_000_beta_0.00.png}\\'
A '      {\tiny RCP source: mode absent --- energy scattered.}'
A '    \column{0.45\textwidth}'
A '      \begin{center}'
A '        {\large Valley Contrast Ratio:}\\[5pt]'
A '        \begin{tikzpicture}'
A '          \node[fill=NYCUblue,text=white,rounded corners=8pt,minimum width=4.5cm,minimum height=1.2cm,font=\LARGE\bfseries]{\highlight{$\approx 112 : 1$}};'
A '        \end{tikzpicture}'
A '      \end{center}'
A '      \vspace{5pt}'
A '      \begin{block}{Physical Origin}'
A '        \begin{itemize}'
A '          \item Structure encodes geometric phase for \textbf{LCP handedness}'
A '          \item RCP cannot satisfy OAM shaping phase condition'
A '          \item Energy scattered into stray modes'
A '        \end{itemize}'
A '      \end{block}'
A '      \vspace{4pt}'
A '      \begin{alertblock}{Significance}'
A '        \begin{itemize}'
A '          \item \textbf{Quantitatively} confirms K/K$'"'"'$ discrimination without external polarization optics'
A '          \item Clear, \textbf{experimentally reproducible} baseline'
A '        \end{itemize}'
A '      \end{alertblock}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% [S26] Physical Limits'
A '\begin{frame}{Discussion: Physical Limits of High-Order OAM}'
A '  \begin{columns}[T]'
A '    \column{0.50\textwidth}'
A '      \begin{alertblock}{Why purity drops for $\ell\ge4$?}'
A '        \textbf{(i) Azimuthal spatial bandwidth limit}\\'
A '        Azimuthal spatial freq.\ $\propto\ell$; at 50\,pts/$\mu$m and 4.5\,$\mu$m, phase gradients approach grid ceiling\\[6pt]'
A '        \textbf{(ii) Design domain too small}\\'
A '        $r_{\rm peak}=w_0\sqrt{\ell/2}$ approaches/exceeds 4.5\,$\mu$m at $\ell=4,5$\\[6pt]'
A '        \textbf{Fix:} expand to $\ge8\,\mu$m\\'
A '        Expected purity $>90\%$ for $\ell=4,5$'
A '      \end{alertblock}'
A '    \column{0.47\textwidth}'
A '      \centering'
A '      \begin{tikzpicture}[font=\small,scale=0.90]'
A '        \fill[gray!25](-2.3,-2.3) rectangle (2.3,2.3);'
A '        \draw[NYCUblue,thick](-2.3,-2.3) rectangle (2.3,2.3);'
A '        \node[NYCUblue,font=\tiny] at (0,-2.55) {4.5\,$\mu$m boundary};'
A '        \draw[accentred,dashed,thick](0,0) circle(1.95);'
A '        \node[accentred,font=\tiny] at (0,2.1) {$r_{\rm peak}$ at $\ell=5$};'
A '        \draw[NYCUgold,dashed,thick](0,0) circle(0.95);'
A '        \node[NYCUgold,font=\tiny] at (0,-1.1) {$r_{\rm peak}$ at $\ell=2$};'
A '        \draw[->,thick,darkgray](-2.6,-2.6)--(2.6,-2.6) node[right]{$x$};'
A '        \draw[->,thick,darkgray](-2.6,-2.6)--(-2.6,2.6) node[above]{$y$};'
A '      \end{tikzpicture}\\[4pt]'
A '      {\tiny LG ring at $\ell=5$ (red) nearly touches design boundary.}'
A '      \vspace{4pt}'
A '      \begin{exampleblock}{Key Note}'
A '        Phase winding $<1\%$ even for $\ell=4,5$\\'
A '        Purity loss = \textbf{intensity non-uniformity},\\'
A '        \textbf{not} topological charge error'
A '      \end{exampleblock}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% [S27] Comparison'
A '\begin{frame}{Comparison with Prior Work}'
A '  \centering\small\renewcommand{\arraystretch}{1.25}'
A '  \begin{tabular}{lcccc}'
A '    \toprule'
A '    \textbf{Work} & \textbf{Design} & \textbf{Purity} & \textbf{Source} & \textbf{Valley sel.} \\'
A '    \midrule'
A '    Karimi 2014 & Forward (PB)      & $\sim$64\%  & Passive PW & \red{None} \\'
A '    Guo 2016    & Forward (PB+prop) & $>$90\%     & Passive PW & \red{None} \\'
A '    Sroor 2020  & Forward, TiO$_2$  & $\sim$90\% ($\ell\!\le\!100$) & Intracavity & \red{None} \\'
A '    Li 2023     & BIC photonic crystal & Not quantified & Active (TMD) & Fixed $\ell$ \\'
A '    \midrule'
A '    \rowcolor{NYCUblue!15}'
A '    \textbf{This work} & \textbf{Inverse (topo.\ opt.)} & \textbf{82--98\%} & \textbf{Active WS$_2$} & \grn{\textbf{$>$100:1}} \\'
A '    \bottomrule'
A '  \end{tabular}'
A '  \vspace{8pt}'
A '  \begin{columns}[T]'
A '    \column{0.32\textwidth}'
A '      \begin{exampleblock}{\centering Advantage (i)}'
A '        \centering\footnotesize \textbf{Active source} + high LG purity ($>$94\% for $\ell\le3$) simultaneously'
A '      \end{exampleblock}'
A '    \column{0.32\textwidth}'
A '      \begin{exampleblock}{\centering Advantage (ii)}'
A '        \centering\footnotesize \textbf{Quantified} valley contrast: RCP 0.84\% vs.\ LCP 94.13\%'
A '      \end{exampleblock}'
A '    \column{0.32\textwidth}'
A '      \begin{exampleblock}{\centering Advantage (iii)}'
A '        \centering\footnotesize $5.1\times10^4$ DOF vs.\ $<$10 params in forward design'
A '      \end{exampleblock}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '\section{Conclusions \& Future Work}'
A ''
A '% [S28] Section Divider'
A '\begin{frame}[plain]'
A '  \begin{tikzpicture}[remember picture,overlay]'
A '    \fill[NYCUblue](current page.south west) rectangle (current page.north east);'
A '    \node[white,font=\Huge\bfseries] at (current page.center){4.\ Conclusions \& Future Work};'
A '  \end{tikzpicture}'
A '\end{frame}'
A ''
A '% [S29] Conclusions'
A '\begin{frame}{Conclusions}'
A '  \begin{enumerate}'
A '    \setlength\itemsep{7pt}'
A '    \item \textbf{High-purity OAM from an active valley source}\\'
A '      Purity $\ge94\%$ for $\ell\le3$; peak \highlight{98.66\%} at $\ell=1$; phase winding error $<1\%$ for all six designs.'
A '    \item \textbf{Spiral geometry self-emerges without any geometric prior}\\'
A '      $\ell$-fold symmetry self-organizes under gradient guidance --- auto-discovered, enriched with scattering compensation.'
A '    \item \textbf{Strong valley selectivity}\\'
A '      K-valley (LCP) 94.13\% vs.\ K$'"'"'$-valley (RCP) 0.84\%; contrast $>$\highlight{100:1}.'
A '    \item \textbf{Near-to-far-field chirality evolution clarified}\\'
A '      Mixed LCP/RCP near field $\to$ pure RCP far field as evanescent waves decay. OAM reshaping and SAM decoupled.'
A '  \end{enumerate}'
A '  \vspace{8pt}'
A '  \begin{center}'
A '    \begin{tikzpicture}'
A '      \node[draw=NYCUblue,fill=lightblue,rounded corners=5pt,minimum width=13.5cm,minimum height=0.9cm,font=\small\bfseries]{First inverse-designed platform: active valley source + high-purity LG mode + quantified inter-valley contrast};'
A '    \end{tikzpicture}'
A '  \end{center}'
A '\end{frame}'
A ''
A '% [S30] Future Work'
A '\begin{frame}{Future Work}'
A '  \begin{columns}[T]'
A '    \column{0.50\textwidth}'
A '      \begin{block}{(i) Expand Design Domain}'
A '        Target $\ge8\,\mu$m + higher resolution\\'
A '        Expected: purity $>90\%$ for $\ell=4,5$'
A '      \end{block}'
A '      \vspace{6pt}'
A '      \begin{block}{(ii) Dual-Valley OAM Multiplexing}'
A '        Single structure: LCP ($K$) $\to+\ell$; RCP ($K'"'"'$) $\to-\ell$\\'
A '        Valley index $\leftrightarrow$ topological charge encoding\\'
A '        Dual-source multi-objective FOM required'
A '      \end{block}'
A '    \column{0.47\textwidth}'
A '      \begin{block}{(iii) Fabrication \& Experiment}'
A '        \begin{itemize}'
A '          \item FDTD tolerance: sidewall $\pm5\,\text{nm}$, etch $\pm5\%$'
A '          \item GaP e-beam lithography + RIE'
A '          \item PL measurement of far-field OAM purity'
A '        \end{itemize}'
A '      \end{block}'
A '      \vspace{6pt}'
A '      \begin{block}{(iv) Purcell Enhancement}'
A '        Photonic crystal cavity $\to$ accelerate radiative rate\\'
A '        Room-T $P_c:\,20$--$50\%\to>80\%$\\'
A '        Expected exp.\ purity $\sim63\%$'
A '      \end{block}'
A '  \end{columns}'
A '  \vspace{5pt}'
A '  \begin{center}'
A '    \small\textbf{\textcolor{NYCUblue}{Vision:}} A chip-scale, valley-programmable, high-purity OAM emitter for next-generation photonic integrated circuits.'
A '  \end{center}'
A '\end{frame}'
A ''
A '% [S31] Thank You'
A '\begin{frame}[plain]'
A '  \vspace{0.5cm}'
A '  \begin{center}'
A '    {\LARGE\textbf{\textcolor{NYCUblue}{Thank You}}}\\[0.6cm]'
A '    {\large\textcolor{darkgray}{Questions \& Discussion}}\\[0.7cm]'
A '    {\color{NYCUblue}\rule{10cm}{1.5pt}}\\[0.5cm]'
A '    {\normalsize \textbf{Cheng, Yin-Jie}\quad|\quad Advisor: Prof.\ Jhih-Sheng Wu\\[4pt] Department of Photonics, NYCU\quad|\quad August 2026}\\[0.5cm]'
A '  \end{center}'
A '  \begin{columns}[c]'
A '    \column{0.30\textwidth}'
A '      \centering'
A '      \includegraphics[width=\textwidth,height=2.4cm,keepaspectratio]{img/018_structure_iter_282_beta_512.00.png}\\'
A '      {\tiny Optimized structure ($\ell=1$)}'
A '    \column{0.38\textwidth}'
A '      \centering'
A '      \begin{tikzpicture}'
A '        \node[draw=NYCUblue,fill=lightblue,rounded corners=5pt,minimum width=5.5cm,minimum height=2.4cm,font=\small,align=center]{Purity: up to \textbf{98.66\%} ($\ell=1$),\\ $>94\%$ for $\ell\le3$\\[4pt] Valley contrast: \textbf{$>$100:1}\\ (94.13\% vs.\ 0.84\%)\\[4pt] Phase winding error: \textbf{$<1\%$} all 6};'
A '      \end{tikzpicture}'
A '    \column{0.30\textwidth}'
A '      \centering'
A '      \includegraphics[width=\textwidth,height=2.4cm,keepaspectratio]{img/018_ff_iter_282_beta_512.00.png}\\'
A '      {\tiny Far-field LG$_{1,0}$ (98.66\%)}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '% Backup Slides'
A '\appendix'
A ''
A '\begin{frame}{Backup: LG Mode Definition \& Performance Metrics}'
A '  \[ u_{p,\ell}(r,\phi,z) = \sqrt{\frac{2p!}{\pi(p+|\ell|)!}} \frac{1}{w}\!\left(\frac{\sqrt{2}r}{w}\right)^{|\ell|} L_p^{|\ell|}\!\!\left(\frac{2r^2}{w^2}\right) e^{-r^2/w^2}\,e^{ikr^2/2R}\,e^{i\ell\phi}\,e^{-i(2p+|\ell|+1)\psi} \]'
A '  \begin{columns}[T]'
A '    \column{0.48\textwidth}'
A '      \begin{block}{Overlap Integral}'
A '        \[ \text{Overlap}=\int_A(E_{ff,x}E_{t,x}^*+E_{ff,y}E_{t,y}^*)\,dA \]'
A '      \end{block}'
A '    \column{0.48\textwidth}'
A '      \begin{block}{Mode Purity}'
A '        \[ \text{Purity}=\frac{|\text{Overlap}|^2}{P_{\rm sim}\cdot P_{\rm target}},\;P_{\rm target}=1 \]'
A '      \end{block}'
A '  \end{columns}'
A '  \vspace{5pt}'
A '  \begin{block}{Phase Winding \& Chirality}'
A '    Winding: sample $\phi(r_{\rm peak},\theta)$, unwrap, compare with $\ell\times2\pi$.\\'
A '    Chirality: $C=\pi f\,\mathrm{Im}(\mathbf{E}^*\cdot\mathbf{H})$.'
A '  \end{block}'
A '\end{frame}'
A ''
A '\begin{frame}{Backup: Valley Selection Rule}'
A '  Under $D_{3h}$ symmetry:'
A '  \[ |\langle u_{c,K}|\hat{p}_+|u_{v,K}\rangle|^2\neq0,\quad |\langle u_{c,K}|\hat{p}_-|u_{v,K}\rangle|^2=0 \]'
A '  \[ |\langle u_{c,K'"'"'}|\hat{p}_+|u_{v,K'"'"'}\rangle|^2=0,\quad |\langle u_{c,K'"'"'}|\hat{p}_-|u_{v,K'"'"'}\rangle|^2\neq0 \]'
A '  \begin{columns}[T]'
A '    \column{0.48\textwidth}'
A '      \begin{block}{Valley Polarization Degree}'
A '        \[ P_c=\frac{I(\sigma^+)-I(\sigma^-)}{I(\sigma^+)+I(\sigma^-)} \]'
A '        Experimentally: 20--50\% at RT; Purcell $\to\sim80\%$'
A '      \end{block}'
A '    \column{0.48\textwidth}'
A '      \begin{alertblock}{Impact on Experiment}'
A '        \[ \text{Purity}_{\rm exp}\approx P_c^2\times\text{Purity}_{\rm sim} \]'
A '        $P_c=80\%$: Purity$_{\rm exp}\approx63\%$'
A '      \end{alertblock}'
A '  \end{columns}'
A '\end{frame}'
A ''
A '\begin{frame}{Backup: Complete Simulation Parameters}'
A '  \centering'
A '  \begin{tabular}{ll}'
A '    \toprule'
A '    \textbf{Parameter} & \textbf{Value} \\'
A '    \midrule'
A '    Wavelength $\lambda$ & $0.593\;\mu$m (WS$_2$ A-exciton) \\'
A '    $n_{\rm GaP}$ & $3.31$ \\'
A '    $n_{\rm Diamond}$ & $2.40$ \\'
A '    Design layer $t$ & $0.257\;\mu$m \\'
A '    Design area & $4.5\times4.5\;\mu\text{m}^2$ \\'
A '    Resolution & $50\;\text{pts}/\mu$m \\'
A '    Design variables $N$ & $226^2\approx5.1\times10^4$ \\'
A '    PML thickness & $0.3\;\mu$m \\'
A '    Min.\ feature size & $0.05\;\mu$m \\'
A '    $\beta$ schedule & $4\to512$ (geometric then $\times2$) \\'
A '    FOM weight $\alpha$ & $0.10$ \\'
A '    Far-field plane & $z=10\,z_R$ \\'
A '    Optimizer & MMA (via NLopt) \\'
A '    Targets & 6 ($\ell=0,1,2,3,4,5$) \\'
A '    \bottomrule'
A '  \end{tabular}'
A '\end{frame}'
A ''
A '\begin{frame}{Backup: Near-Field Phase \& Intensity (All 6)}'
A '  \centering'
A '  {\footnotesize Near-field monitor plane. Each panel: phase(L)+intensity(R).}\\[4pt]'
A '  \begin{tabular}{ccc}'
A '    \includegraphics[width=0.31\textwidth,keepaspectratio]{img/017_phase_iter_257_beta_512.00.png} &'
A '    \includegraphics[width=0.31\textwidth,keepaspectratio]{img/018_phase_iter_282_beta_512.00.png} &'
A '    \includegraphics[width=0.31\textwidth,keepaspectratio]{img/013_phase_iter_282_beta_512.00.png} \\'
A '    {\tiny (a) $\ell=0$} & {\tiny (b) $\ell=1$} & {\tiny (c) $\ell=2$} \\[4pt]'
A '    \includegraphics[width=0.31\textwidth,keepaspectratio]{img/020_phase_iter_282_beta_512.00.png} &'
A '    \includegraphics[width=0.31\textwidth,keepaspectratio]{img/021_phase_iter_267_beta_512.00.png} &'
A '    \includegraphics[width=0.31\textwidth,keepaspectratio]{img/022_phase_iter_282_beta_512.00.png} \\'
A '    {\tiny (d) $\ell=3$} & {\tiny (e) $\ell=4$} & {\tiny (f) $\ell=5$} \\'
A '  \end{tabular}'
A '\end{frame}'
A ''
A '\begin{frame}{Backup: Far-Field Chirality (All 6)}'
A '  \centering'
A '  {\footnotesize Far-field chirality at $z=10\,z_R$. Pure RCP in beam spot for all designs.}\\[4pt]'
A '  \begin{tabular}{ccc}'
A '    \includegraphics[width=0.31\textwidth,keepaspectratio]{img/017_ff_chirality_257_beta_512.00.png} &'
A '    \includegraphics[width=0.31\textwidth,keepaspectratio]{img/018_ff_chirality_282_beta_512.00.png} &'
A '    \includegraphics[width=0.31\textwidth,keepaspectratio]{img/013_ff_chirality_282_beta_512.00.png} \\'
A '    {\tiny (a) $\ell=0$} & {\tiny (b) $\ell=1$} & {\tiny (c) $\ell=2$} \\[4pt]'
A '    \includegraphics[width=0.31\textwidth,keepaspectratio]{img/020_ff_chirality_282_beta_512.00.png} &'
A '    \includegraphics[width=0.31\textwidth,keepaspectratio]{img/021_ff_chirality_267_beta_512.00.png} &'
A '    \includegraphics[width=0.31\textwidth,keepaspectratio]{img/022_ff_chirality_282_beta_512.00.png} \\'
A '    {\tiny (d) $\ell=3$} & {\tiny (e) $\ell=4$} & {\tiny (f) $\ell=5$} \\'
A '  \end{tabular}'
A '\end{frame}'
A ''
A '\end{document}'

$lines | Set-Content -Path $out -Encoding UTF8
Write-Host "Written $($lines.Count) lines to $out"
